on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release version"
        type: choice
        required: true
        options:
          - patch
          - minor
          - major

name: Release Extension

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - id: bump-version
        run: |
          npm version ${{ inputs.release }} | xargs -I% echo "::set-output name=version::%"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: release ${{ steps.bump-version.outputs.version }}
          tagging_message: ${{ steps.bump-version.outputs.version }}
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          packagePath: ./extension
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
